export const constellationStylesDesktop = {
  constellation1: {
    constellation: {
      position: "absolute",
      height: 147,
      width: 276,
      left: "calc(50% - 276px/2 - 360px)",
      top: "calc(50% - 147px/2 - 254.5px)",
    },
    constellationImage: {
      position: "absolute",
      width: "80%",
      height: "80%",
      backgroundImage: "url(" + require("./assets/constellation1.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.5)",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "5%",
      left: "45%",
      width: "max-content",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
  constellation2: {
    constellation: {
      position: "absolute",
      height: 181,
      width: 237,
      left: "calc(50% - 237px/2 + 19.5px)",
      top: "calc(50% - 181px/2 + 281.5px)",
    },
    constellationImage: {
      position: "absolute",
      height: "80%",
      width: "80%",
      backgroundImage: "url(" + require("./assets/constellation2.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.5)",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "10%",
      left: "90%",
      width: "max-content",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
  constellation3: {
    constellation: {
      position: "absolute",
      height: 299,
      width: 167,
      left: "calc(50% - 167px/2 - 570.5px)",
      top: "calc(50% - 299px/2 - 55.5px)",
    },
    constellationImage: {
      position: "absolute",
      height: "80%",
      width: "80%",
      backgroundImage: "url(" + require("./assets/constellation3.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.5)",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "10%",
      left: "75%",
      width: "max-content",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
  constellation4: {
    constellation: {
      position: "absolute",
      height: 187,
      width: 275,
      left: "calc(50% - 275px/2 + 459.5px)",
      top: "calc(50% - 187px/2 - 126.5px)",
    },
    constellationImage: {
      position: "absolute",
      height: "80%",
      width: "80%",
      backgroundImage: "url(" + require("./assets/constellation4.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.5)",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "-20%",
      left: "30%",
      width: "max-content",
      maxWidth: 400,
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
  constellation5: {
    constellation: {
      position: "absolute",
      height: 254,
      width: 196,
      left: "calc(50% - 196px/2 + 42px)",
      top: "calc(50% - 254px/2 + 298px)",
    },
    constellationImage: {
      position: "absolute",
      height: "80%",
      width: "80%",
      backgroundImage: "url(" + require("./assets/constellation5.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.5)",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "40%",
      left: "90%",
      width: "max-content",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
  constellation6: {
    constellation: {
      position: "absolute",
      height: 195,
      width: 298,
    },
    constellationImage: {
      position: "absolute",
      height: "80%",
      width: "80%",
      backgroundImage: "url(" + require("./assets/constellation6.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.5)",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "-30%",
      left: "30%",
      width: "max-content",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
  constellation7: {
    constellation: {
      height: 322,
      width: 243,
      left: "calc(50% - 243px/2 - 481.5px)",
      top: "calc(50% - 322px/2 + 226px)",
    },
    constellationImage: {
      width: "80%",
      height: "80%",
      backgroundImage: "url(" + require("./assets/constellation7.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.5)",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "30%",
      left: "80%",
      width: "max-content",
      maxWidth: 430,
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
  constellation8: {
    constellation: {
      position: "absolute",
      height: 199,
      width: 222,
      left: "calc(50% - 222px/2 - 608px)",
      top: "calc(50% - 199px/2 - 66.5px)",
    },
    constellationImage: {
      position: "absolute",
      height: "80%",
      width: "80%",
      backgroundImage: "url(" + require("./assets/constellation8.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.5)",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "-5%",
      left: "120%",
      width: "max-content",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
  constellation9: {
    constellation: {
      position: "absolute",
      height: 206,
      width: 310,
      left: "calc(50% - 310px/2 + 480px)",
      top: "calc(50% - 206px/2 + 241px)",
    },
    constellationImage: {
      position: "absolute",
      width: "80%",
      height: "80%",
      backgroundImage: "url(" + require("./assets/constellation9.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.5)",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "-32%",
      left: "20%",
      width: "max-content",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
};
