export const constellationStylesDesktop = {
  constellation1: {
    constellation: {
      position: "absolute",
      height: 147,
      width: 276,
      left: "calc(50% - 276px/2 - 360px)",
      top: "calc(50% - 147px/2 - 254.5px)",
      "@media (max-height:1080px)": {
        left: "calc(50% - 46.11vh)",
        top: "calc(50% - 30.37vh)",
      },
    },
    constellationImage: {
      position: "absolute",
      zIndex: 20,
      width: "80%",
      height: "80%",
      backgroundImage: "url(" + require("./assets/constellation1.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.2)",
        backgroundImage:
          "url(" + require("./assets/constellation1hoverstate.png") + ")",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.2rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "5%",
      left: "45%",
      width: "max-content",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
  constellation2: {
    constellation: {
      position: "absolute",
      height: 181,
      width: 237,
      left: "calc(50% - 237px/2 + 19.5px)",
      top: "calc(50% - 181px/2 + 281.5px)",
      "@media (max-height:1080px)": {
        left: "calc(50% - 9.17vh)",
        top: "calc(50% + 17.69vh)",
      },
    },
    constellationImage: {
      position: "absolute",
      zIndex: 20,
      height: "80%",
      width: "80%",
      backgroundImage: "url(" + require("./assets/constellation2.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.2)",
        backgroundImage:
          "url(" + require("./assets/constellation2hoverstate.png") + ")",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.2rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "10%",
      left: "90%",
      width: "max-content",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
  constellation3: {
    constellation: {
      position: "absolute",
      height: 299,
      width: 167,
      left: "calc(50% - 167px/2 - 570.5px)",
      top: "calc(50% - 299px/2 - 55.5px)",
      "@media (max-height:1080px)": {
        left: "calc(50% - 60.56vh)",
        top: "calc(50% - 18.98vh)",
      },
    },
    constellationImage: {
      position: "absolute",
      zIndex: 20,
      height: "80%",
      width: "80%",
      backgroundImage: "url(" + require("./assets/constellation3.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.2)",
        backgroundImage:
          "url(" + require("./assets/constellation3hoverstate.png") + ")",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.2rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "10%",
      left: "40%",
      width: "300px",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
  constellation4: {
    constellation: {
      position: "absolute",
      height: 187,
      width: 275,
      left: "calc(50% - 275px/2 + 459.5px)",
      top: "calc(50% - 187px/2 - 126.5px)",
      "@media (max-height:1080px)": {
        left: "calc(50% + 29.81vh)",
        top: "calc(50% - 20.37vh)",
      },
    },
    constellationImage: {
      position: "absolute",
      zIndex: 20,
      height: "80%",
      width: "80%",
      backgroundImage: "url(" + require("./assets/constellation4.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.2)",
        backgroundImage:
          "url(" + require("./assets/constellation4hoverstate.png") + ")",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.2rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "-20%",
      left: "30%",
      width: "max-content",
      maxWidth: 250,
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
  constellation5: {
    constellation: {
      position: "absolute",
      height: 254,
      width: 196,
      left: "calc(50% - 196px/2 + 42px)",
      top: "calc(50% - 254px/2 + 298px)",
      "@media (max-height:1080px)": {
        left: "calc(50% - 5.19vh)",
        top: "calc(50% + 15.83vh)",
      },
    },
    constellationImage: {
      position: "absolute",
      zIndex: 20,
      height: "80%",
      width: "80%",
      backgroundImage: "url(" + require("./assets/constellation5.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.2)",
        backgroundImage:
          "url(" + require("./assets/constellation5hoverstate.png") + ")",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.2rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "40%",
      left: "90%",
      width: 400,
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
  constellation6: {
    constellation: {
      position: "absolute",
      height: 195,
      width: 298,
      left: "calc(50% - 298px/2 + 403px)",
      top: "calc(50% - 195px/2 - 165.5px)",
      "@media (max-height:1080px)": {
        left: "calc(50% + 23.52vh)",
        top: "calc(50% - 24.35vh)",
      },
    },
    constellationImage: {
      position: "absolute",
      zIndex: 20,
      height: "80%",
      width: "80%",
      backgroundImage: "url(" + require("./assets/constellation6.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.2)",
        backgroundImage:
          "url(" + require("./assets/constellation6hoverstate.png") + ")",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.2rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "-30%",
      left: "30%",
      width: "max-content",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
  constellation7: {
    constellation: {
      height: 322,
      width: 243,
      left: "calc(50% - 243px/2 - 481.5px)",
      top: "calc(50% - 322px/2 + 226px)",
      "@media (max-height:1080px)": {
        left: "calc(50% - 55.83vh)",
        top: "calc(50% + 6.02vh)",
      },
    },
    constellationImage: {
      width: "80%",

      zIndex: 20,
      height: "80%",
      backgroundImage: "url(" + require("./assets/constellation7.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.2)",
        backgroundImage:
          "url(" + require("./assets/constellation7hoverstate.png") + ")",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.2rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "30%",
      left: "70%",
      width: "max-content",
      maxWidth: 350,
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
  constellation8: {
    constellation: {
      position: "absolute",
      height: 199,
      width: 222,
      left: "calc(50% - 222px/2 - 608px)",
      top: "calc(50% - 199px/2 - 66.5px)",
      "@media (max-height:1080px)": {
        left: "calc(50% - 66.57vh)",
        top: "calc(50% - 15.37vh)",
      },
    },
    constellationImage: {
      position: "absolute",
      zIndex: 20,
      height: "80%",
      width: "80%",
      backgroundImage: "url(" + require("./assets/constellation8.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.2)",
        backgroundImage:
          "url(" + require("./assets/constellation8hoverstate.png") + ")",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.2rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "-30%",
      left: "40%",
      width: "350px",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
  constellation9: {
    constellation: {
      position: "absolute",
      height: 206,
      width: 310,
      left: "calc(50% - 310px/2 + 480px)",
      top: "calc(50% - 206px/2 + 241px)",
      "@media (max-height:1080px)": {
        left: "calc(50% + 30.09vh)",
        top: "calc(50% + 12.78vh)",
      },
    },
    constellationImage: {
      position: "absolute",
      width: "80%",
      height: "80%",
      backgroundImage: "url(" + require("./assets/constellation9.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.2)",
        backgroundImage:
          "url(" + require("./assets/constellation9hoverstate.png") + ")",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.2rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "-30%",
      left: "0",
      maxWidth: 350,
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
};

export const constellationStylesIPad = {
  constellation1: {
    constellation: {
      position: "absolute",
      height: 147,
      width: 276,
      left: "calc(50% - 276px/2 - 360px)",
      top: "calc(50% - 147px/2 - 254.5px)",

      "@media  (max-width: 1200px)": {
        position: "none",
        left: "0px",
        right: "0px",
        top: "0px",
        bottom: "0px",
        display: "flex",
        flexDirection: "column",
        margin: "auto",
        width: "80%",
        height: "80%",
        padding: "auto",
      },
    },
    constellationImage: {
      position: "absolute",
      zIndex: 20,
      width: "80%",
      height: "80%",
      backgroundImage: "url(" + require("./assets/constellation1.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.3)",
        backgroundImage:
          "url(" + require("./assets/constellation1hoverstate.png") + ")",
      },
      "@media  (max-width: 1200px)": {
        position: "relative",
        margin: "auto",
        padding: "0",
        width: "100%",
        backgroundSize: "50%",
        top: "10%",
      },
      "@media  (max-width: 600px)": {
        top: "10%",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
      "@media  (max-width: 1200px)": {
        display: "flex",
        justifyContent: "center",
        margin: "auto",
        width: "50%",
        bottom: "0",
        left: "0",
        right: "0",
      },
      "@media  (max-width: 600px)": {
        width: "100%",
        fontSize: "1.2rem",
      },
    },
  },
  constellation2: {
    constellation: {
      position: "absolute",
      height: 147,
      width: 276,
      left: "calc(50% - 276px/2 - 360px)",
      top: "calc(50% - 147px/2 - 254.5px)",

      "@media  (max-width: 1200px)": {
        position: "none",
        left: "0px",
        right: "0px",
        top: "0px",
        bottom: "0px",
        display: "flex",
        flexDirection: "column",
        margin: "auto",
        width: "80%",
        height: "80%",
        padding: "auto",
      },
    },
    constellationImage: {
      position: "absolute",
      zIndex: 20,
      width: "80%",
      height: "80%",
      backgroundImage: "url(" + require("./assets/constellation2.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.3)",
        backgroundImage:
          "url(" + require("./assets/constellation2hoverstate.png") + ")",
      },
      "@media  (max-width: 1200px)": {
        position: "relative",
        margin: "auto",
        padding: "0",
        width: "100%",
        backgroundSize: "50%",
        top: "10%",
      },
      "@media  (max-width: 600px)": {
        top: "10%",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "5%",
      left: "45%",
      width: "max-content",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
      "@media  (max-width: 1200px)": {
        display: "flex",
        justifyContent: "center",
        margin: "auto",
        width: "50%",
        bottom: "0",
        left: "0",
        right: "0",
      },
      "@media  (max-width: 600px)": {
        width: "100%",
        fontSize: "1.2rem",
      },
    },
  },
  constellation3: {
    constellation: {
      position: "absolute",
      height: 147,
      width: 276,
      left: "calc(50% - 276px/2 - 360px)",
      top: "calc(50% - 147px/2 - 254.5px)",

      "@media  (max-width: 1200px)": {
        position: "none",
        left: "0px",
        right: "0px",
        top: "0px",
        bottom: "0px",
        display: "flex",
        flexDirection: "column",
        margin: "auto",
        width: "80%",
        height: "80%",
        padding: "auto",
      },
    },
    constellationImage: {
      position: "absolute",
      zIndex: 20,
      width: "80%",
      height: "80%",
      backgroundImage: "url(" + require("./assets/constellation3.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.3)",
        backgroundImage:
          "url(" + require("./assets/constellation3hoverstate.png") + ")",
      },
      "@media  (max-width: 1200px)": {
        position: "relative",
        margin: "auto",
        padding: "0",
        width: "100%",
        backgroundSize: "25%",
        top: "10%",
      },
      "@media  (max-width: 600px)": {
        top: "10%",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "5%",
      left: "45%",
      width: "max-content",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
      "@media  (max-width: 1200px)": {
        display: "flex",
        justifyContent: "center",
        margin: "auto",
        width: "50%",
        bottom: "0",
        left: "0",
        right: "0",
      },
      "@media  (max-width: 600px)": {
        width: "100%",
        fontSize: "1.2rem",
      },
    },
  },
  constellation4: {
    constellation: {
      position: "absolute",
      height: 147,
      width: 276,
      left: "calc(50% - 276px/2 - 360px)",
      top: "calc(50% - 147px/2 - 254.5px)",

      "@media  (max-width: 1200px)": {
        position: "none",
        left: "0px",
        right: "0px",
        top: "0px",
        bottom: "0px",
        display: "flex",
        flexDirection: "column",
        margin: "auto",
        width: "80%",
        height: "80%",
        padding: "auto",
      },
    },
    constellationImage: {
      position: "absolute",
      zIndex: 20,
      width: "80%",
      height: "80%",
      backgroundImage: "url(" + require("./assets/constellation4.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.3)",
        backgroundImage:
          "url(" + require("./assets/constellation4hoverstate.png") + ")",
      },
      "@media  (max-width: 1200px)": {
        position: "relative",
        margin: "auto",
        padding: "0",
        width: "100%",
        backgroundSize: "50%",
        top: "10%",
      },
      "@media  (max-width: 600px)": {
        top: "10%",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "5%",
      left: "45%",
      width: "max-content",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
      "@media  (max-width: 1200px)": {
        display: "flex",
        justifyContent: "center",
        margin: "auto",
        width: "50%",
        bottom: "0",
        left: "0",
        right: "0",
      },
      "@media  (max-width: 600px)": {
        width: "100%",
        fontSize: "1.2rem",
      },
    },
  },
  constellation5: {
    constellation: {
      position: "absolute",
      height: 147,
      width: 276,
      left: "calc(50% - 276px/2 - 360px)",
      top: "calc(50% - 147px/2 - 254.5px)",

      "@media  (max-width: 1200px)": {
        position: "none",
        left: "0px",
        right: "0px",
        top: "0px",
        bottom: "0px",
        display: "flex",
        flexDirection: "column",
        margin: "auto",
        width: "80%",
        height: "80%",
        padding: "auto",
      },
    },
    constellationImage: {
      position: "absolute",
      zIndex: 20,
      width: "80%",
      height: "80%",
      backgroundImage: "url(" + require("./assets/constellation5.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.3)",
        backgroundImage:
          "url(" + require("./assets/constellation5hoverstate.png") + ")",
      },
      "@media  (max-width: 1200px)": {
        position: "relative",
        margin: "auto",
        padding: "0",
        width: "100%",
        backgroundSize: "30%",
        top: "10%",
      },
      "@media  (max-width: 600px)": {
        top: "10%",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "5%",
      left: "45%",
      width: "max-content",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
      "@media  (max-width: 1200px)": {
        display: "flex",
        justifyContent: "center",
        margin: "auto",
        width: "50%",
        bottom: "0",
        left: "0",
        right: "0",
      },
      "@media  (max-width: 600px)": {
        width: "100%",
        fontSize: "1.2rem",
      },
    },
  },
  constellation6: {
    constellation: {
      position: "absolute",
      height: 147,
      width: 276,
      left: "calc(50% - 276px/2 - 360px)",
      top: "calc(50% - 147px/2 - 254.5px)",

      "@media  (max-width: 1200px)": {
        position: "none",
        left: "0px",
        right: "0px",
        top: "0px",
        bottom: "0px",
        display: "flex",
        flexDirection: "column",
        margin: "auto",
        width: "80%",
        height: "80%",
        padding: "auto",
      },
    },
    constellationImage: {
      position: "absolute",
      zIndex: 20,
      width: "80%",
      height: "80%",
      backgroundImage: "url(" + require("./assets/constellation6.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.3)",
        backgroundImage:
          "url(" + require("./assets/constellation6hoverstate.png") + ")",
      },
      "@media  (max-width: 1200px)": {
        position: "relative",
        margin: "auto",
        padding: "0",
        width: "100%",
        backgroundSize: "50%",
        top: "10%",
      },
      "@media  (max-width: 600px)": {
        top: "10%",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "5%",
      left: "45%",
      width: "max-content",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
      "@media  (max-width: 1200px)": {
        display: "flex",
        justifyContent: "center",
        margin: "auto",
        width: "50%",
        bottom: "0",
        left: "0",
        right: "0",
      },
      "@media  (max-width: 600px)": {
        width: "100%",
        fontSize: "1.2rem",
      },
    },
  },
  constellation7: {
    constellation: {
      position: "absolute",
      height: 147,
      width: 276,
      left: "calc(50% - 276px/2 - 360px)",
      top: "calc(50% - 147px/2 - 254.5px)",

      "@media  (max-width: 1200px)": {
        position: "none",
        left: "0px",
        right: "0px",
        top: "0px",
        bottom: "0px",
        display: "flex",
        flexDirection: "column",
        margin: "auto",
        width: "80%",
        height: "80%",
        padding: "auto",
      },
    },
    constellationImage: {
      position: "absolute",
      zIndex: 20,
      width: "80%",
      height: "80%",
      backgroundImage: "url(" + require("./assets/constellation7.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.3)",
        backgroundImage:
          "url(" + require("./assets/constellation7hoverstate.png") + ")",
      },
      "@media  (max-width: 1200px)": {
        position: "relative",
        margin: "auto",
        padding: "0",
        width: "100%",
        top: "10%",
        backgroundSize: "30%",
      },
      "@media  (max-width: 600px)": {
        top: "10%",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "5%",
      left: "45%",
      width: "max-content",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
      "@media  (max-width: 1200px)": {
        display: "flex",
        justifyContent: "center",
        margin: "auto",
        width: "50%",
        bottom: "0",
        left: "0",
        right: "0",
      },
      "@media  (max-width: 600px)": {
        width: "100%",
        fontSize: "1.2rem",
      },
    },
  },
  constellation8: {
    constellation: {
      position: "absolute",
      height: 147,
      width: 276,
      left: "calc(50% - 276px/2 - 360px)",
      top: "calc(50% - 147px/2 - 254.5px)",

      "@media  (max-width: 1200px)": {
        position: "none",
        left: "0px",
        right: "0px",
        top: "0px",
        bottom: "0px",
        display: "flex",
        flexDirection: "column",
        margin: "auto",
        width: "80%",
        height: "80%",
        padding: "auto",
      },
    },
    constellationImage: {
      position: "absolute",
      zIndex: 20,
      width: "80%",
      height: "80%",
      backgroundImage: "url(" + require("./assets/constellation8.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.3)",
        backgroundImage:
          "url(" + require("./assets/constellation8hoverstate.png") + ")",
      },
      "@media  (max-width: 1200px)": {
        position: "relative",
        margin: "auto",
        padding: "0",
        width: "100%",
        backgroundSize: "40%",
        top: "10%",
      },
      "@media  (max-width: 600px)": {
        top: "10%",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "5%",
      left: "45%",
      width: "max-content",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
      "@media  (max-width: 1200px)": {
        display: "flex",
        justifyContent: "center",
        margin: "auto",
        width: "50%",
        bottom: "0",
        left: "0",
        right: "0",
      },
      "@media  (max-width: 600px)": {
        width: "100%",
        fontSize: "1.2rem",
      },
    },
  },
  constellation9: {
    constellation: {
      position: "absolute",
      height: 147,
      width: 276,
      left: "calc(50% - 276px/2 - 360px)",
      top: "calc(50% - 147px/2 - 254.5px)",

      "@media  (max-width: 1200px)": {
        position: "none",
        left: "0px",
        right: "0px",
        top: "0px",
        bottom: "0px",
        display: "flex",
        flexDirection: "column",
        margin: "auto",
        width: "80%",
        height: "80%",
        padding: "auto",
      },
    },
    constellationImage: {
      position: "absolute",
      zIndex: 20,
      width: "80%",
      height: "80%",
      backgroundImage: "url(" + require("./assets/constellation9.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.3)",
        backgroundImage:
          "url(" + require("./assets/constellation9hoverstate.png") + ")",
      },
      "@media  (max-width: 1200px)": {
        position: "relative",
        margin: "auto",
        padding: "0",
        width: "100%",
        backgroundSize: "50%",
        top: "10%",
      },
      "@media  (max-width: 600px)": {
        top: "10%",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "5%",
      left: "45%",
      width: "max-content",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
      "@media  (max-width: 1200px)": {
        display: "flex",
        justifyContent: "center",
        margin: "auto",
        width: "50%",
        bottom: "0",
        left: "0",
        right: "0",
      },
      "@media  (max-width: 600px)": {
        width: "100%",
        fontSize: "1.2rem",
      },
    },
  },
};
