export const constellationStylesDesktop = {
  constellation1: {
    constellation: {
      position: "absolute",
      height: 147,
      width: 276,
    },
    constellationImage: {
      position: "absolute",
      width: "80%",
      height: "80%",
      backgroundImage: "url(" + require("./assets/constellation1.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.5)",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "5%",
      left: "45%",
      width: "max-content",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
  constellation2: {
    constellation: {
      position: "absolute",
      height: 181,
      width: 237,
    },
    constellationImage: {
      position: "absolute",
      height: "80%",
      width: "80%",
      backgroundImage: "url(" + require("./assets/constellation2.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.5)",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "10%",
      left: "90%",
      width: "max-content",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
  constellation3: {
    constellation: {
      position: "absolute",
      height: 299,
      width: 167,
    },
    constellationImage: {
      position: "absolute",
      height: "80%",
      width: "80%",
      backgroundImage: "url(" + require("./assets/constellation3.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.5)",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "10%",
      left: "75%",
      width: "max-content",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
  constellation4: {
    constellation: {
      position: "absolute",
      height: 187,
      width: 275,
    },
    constellationImage: {
      position: "absolute",
      height: "80%",
      width: "80%",
      backgroundImage: "url(" + require("./assets/constellation4.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.5)",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "-20%",
      left: "30%",
      width: "max-content",
      maxWidth: 400,
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
  constellation5: {
    constellation: {
      position: "absolute",
      height: 254,
      width: 196,
    },
    constellationImage: {
      position: "absolute",
      height: "80%",
      width: "80%",
      backgroundImage: "url(" + require("./assets/constellation5.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.5)",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "40%",
      left: "90%",
      width: "max-content",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
  constellation6: {
    constellation: {
      position: "absolute",
      height: 195,
      width: 298,
    },
    constellationImage: {
      position: "absolute",
      height: "80%",
      width: "80%",
      backgroundImage: "url(" + require("./assets/constellation6.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.5)",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "-30%",
      left: "30%",
      width: "max-content",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
  constellation7: {
    constellation: {
      height: 322,
      width: 243,
    },
    constellationImage: {
      width: "80%",
      height: "80%",
      backgroundImage: "url(" + require("./assets/constellation7.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.5)",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "30%",
      left: "80%",
      width: "max-content",
      maxWidth: 430,
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
  constellation8: {
    constellation: {
      position: "absolute",
      height: 199,
      width: 222,
    },
    constellationImage: {
      position: "absolute",
      height: "80%",
      width: "80%",
      backgroundImage: "url(" + require("./assets/constellation8.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.5)",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "-5%",
      left: "120%",
      width: "max-content",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
  constellation9: {
    constellation: {
      position: "absolute",
      height: 206,
      width: 310,
    },
    constellationImage: {
      position: "absolute",
      width: "80%",
      height: "80%",
      backgroundImage: "url(" + require("./assets/constellation9.png") + ")",
      backgroundRepeat: "no-repeat",
      backgroundPosition: "center",
      backgroundSize: "cover",
      transition: "transform .4s",
      "&:hover": {
        transform: "scale(1.5)",
      },
    },
    subfieldName: {
      position: "relative",
      color: "white",
      fontFamily: "Montserrat",
      fontSize: "1.5rem",
      letterSpacing: 2.6,
      fontWeight: "bold",
      top: "-32%",
      left: "20%",
      width: "max-content",
      transition: "text-shadow 0.2s linear",
      "&:hover": {
        textShadow: "0 0 50px white",
      },
    },
  },
};
