export default {
  login: "/login",
  error404: "/not-found",
  home: "/",
  explore: "/explore",
  faq: "/faq",
  mission: "/ourmission",
  terms: "/termsandconditions",
  model: "/ourmodel",
  contact: "/contactus",
  team: "/ourteam",
  informationPageX: "/topicx",
  projectX: "/projectx",
  biology: "/explore/biology",
  physics: "/explore/physics",
  mathsAndStats: "/explore/mathematicsandstats",
  spaceSciences: "/explore/spacesciences",
  computerScience: "/explore/computerscience",
  earthSciences: "/explore/earthsciences",
  chemistry: "/explore/chemistry",
  medicine: "/explore/medicine",
  socialSciences: "/explore/socialsciences",
  engineeringAndTech: "/explore/engineeringandtech",
};
