export default {
  login: "/login",
  error404: "/not-found",
  home: "/",
  explore: "/explore",
  faq: "/faq",
  mission: "/ourmission",
  terms: "/termsandconditions",
  model: "/ourmodel",
  contact: "/contactus",
  team: "/ourteam",
  informationPageX: "/topicx",
  biology: "/explore/biology",
  socialsciences: "/explore/socialsciences",
  physics: "/explore/physics",
  mathematicsandstats: "/explore/mathematicsandstats",
  spacesciences: "/explore/spacesciences",
  computerscience: "/explore/computerscience",
  engineeringandtech: "/explore/engineeringandtech",
  earthsciences: "/explore/earthsciences",
  chemistry: "/explore/chemistry",
  medicine: "/explore/medicine",
};
